name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [14.x]
    env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        rm -rf .npmrc
        cat <<EOF > .npmrc
        @excalibur-enterprise:registry=https://npm.pkg.github.com
        //npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}
        EOF
        npm install
    - name: Run ESLint
      run: npm run lint
    - name: Run Build
      run: npm run build
