name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@excalibur-enterprise'
    - name: npm install
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Run Build
      run: npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
