name: Publish Package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Build
      run: |
        rm -rf .npmrc
        cat <<EOF > .npmrc
        @excalibur-enterprise:registry=https://npm.pkg.github.com
        //npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}
        EOF
        npm install && npm run build
    
    - name: Run Tests
      run: npm run test
    
    - name: Publish
      run: |
        npm version ${GITHUB_REF#refs\/tags\/v} --no-git-tag-version --allow-same-version && \
        npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_PUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUB_TOKEN }}
